apiVersion: v1
kind: Service
metadata:
  name: bradenp-test-redis-service
  labels:
    username: bradenp
    env: test
spec:
  type: ClusterIP
  # clusterIP: 10.104.165.3 # Remove comment and change IP accordingly to force an IP for the redis service
  selector:
    username: bradenp
    env: test
    app: bradenp-test-redis
  ports:
  - name: bradenp-test-redis
    port: 6379
    targetPort: 6379