---
apiVersion: v1
kind: Service
metadata:
  name: bradenp-test-flask-service
  labels:
    username: bradenp
    env: test
spec:
  type: ClusterIP
  selector:
    username: bradenp
    env: test
    app: bradenp-test-flask
  ports:
  - name: bradenp-test-flask
    port: 5000
    targetPort: 5000