version: '3'
services:    
      web_bsp:
        build: ./flask
        container_name: web_bsp
        ports:
           - 5026:5000
        volumes:
           - ./flask/mydata:/mydata
      redis:
        image: redis:latest
        ports:
           - 6406:6379
        volumes:
           - ./redis/config/redis.conf:/redis.conf
           - ./redis/datum/:/data
        user: "869731:816966"
        command: [ "redis-server", "/redis.conf" ]