---
apiVersion: v1
kind: Service
metadata:
  name: bradenp-hw7-flask-service
  labels:
    username: bradenp
    env: hw7
spec:
  type: ClusterIP
  selector:
    username: bradenp
    env: hw7
    app: bradenp-hw7-flask
  ports:
  - name: bradenp-hw7-flask
    port: 5000
    targetPort: 5000